title: Screem-Sec
email: hello@screem-sec.com
description: Cybersecurity, write-ups and anything else that interests me.
paginate: 5
baseUrl: https://screem-sec.com/

# Socials
mastodon: https://infosec.exchange/@screem
github: https://github.com/Screem-Sec/
